Repository microsoft/accessibility-insights-service, pull requests merged in 2020-04, with the labels that each got.

#692 chore: Mark scans that failed to enqueue as failure with error info
  packages/storage-documents/src/on-demand-page-scan-result.ts
  packages/web-api-scan-request-sender/package.json
  packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts
  packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.ts
Labels: pr: auto-merge

#693 chore: increase max queue size
  packages/resource-deployment/runtime-config/runtime-config.ppe.json
  packages/resource-deployment/runtime-config/runtime-config.prod.json
Labels: pr: auto-merge

#695 chore: decrease wait time for logging open handles
  packages/web-api-scan-job-manager/src/index.ts
  packages/web-api-scan-request-sender/src/index.ts
  packages/web-api-scan-runner/src/index.ts
  packages/web-api-send-notification-job-manager/src/index.ts
  packages/web-api-send-notification-runner/src/index.ts
Labels: pr: DO NOT MERGE

#730 chore (deps): using cpy-cli instead of cpx package
  packages/resource-deployment/package.json
  packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts
  yarn.lock
Labels: dependencies
